kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: C:\Users\USER\development\camunda    # Change this to your desired host path
    containerPath: /data